name: Production deployment with pm2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: start server with pm2
        id: start-step
        run: pm2 start 0

      - name: restart nginx
        id: restart-nginx
        run: sudo service nginx restart
        continue-on-error: true

  notify:
    name: Notify Telegram Group
    runs-on: self-hosted
    needs: build
    if: always() # Barcha testlar tugagandan keyin bajariladi
    steps:
      - name: Transpile typescript to javascript
        run: |
          npx tsc index.ts

      - name: Notify telegram group on failure integration test
        run: |
          node index.js release ${{ steps.restart-nginx.outcome }}
