name: Production deployment with pm2

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: start server with pm2
        id: start_step
        run: pm2 start 0

      - name: Transpile typescript to javascript
        run: |
          npx tsc index.ts

      - name: Notify telegram group on failure integration test
        run: |
          node index.js release ${{ steps.start_step.outcome }}
